# resources
cuda: false
fp16: false

# env
vecenv: true
numenv: 4

# logging
wandb_project: "damnlemons"
record: false
render: false

# training
num_timesteps: 10000000
training_steps_per_iter: 2
eval_steps_per_iter: 10
eval_every: 100

# model
layer_norm: true

# optimization
actor_lr: 2.5e-4
critic_lr: 2.5e-4
clip_norm: 40.
wd_scale: 0.

# algorithm
segment_len: 2
batch_size: 64
gamma: 0.99
mem_size: 100000
polyak: 0.005
targ_up_freq: 100
n_step_returns: true
lookahead: 5
ret_norm: false

# TD3
normal_noise_std: 0.1
clipped_double: true
bcq_style_targ_mix: true
targ_actor_smoothing: true
td3_std: 0.2
td3_c: 0.5
actor_update_delay: 2

# SAC
state_dependent_std: true
use_adaptive_alpha: true
log_alpha_lr: 3.0e-4
init_temp_log_alpha: 0.1
crit_targ_update_freq: 1

# distributional RL
use_c51: false
use_qr: false
c51_num_atoms: 51
c51_vmin: -100.
c51_vmax: 100.
num_tau: 200

# AIL
g_steps: 1
d_steps: 1
d_lr: 5.0e-4
state_only: false
minimax_only: true
d_label_smooth: 0.25
ent_reg_scale: 0.0001
spectral_norm: true
grad_pen: true
grad_pen_targ: 1.
grad_pen_scale: 10.
one_sided_pen: true
historical_patching: true
wrap_absorb: true
d_batch_norm: false
